# Generated by Django 5.1.1 on 2024-09-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Торты', 'Торты'), ('Печенье', 'Печенье'), ('Выпечка', 'Выпечка'), ('Шоколад', 'Шоколад'), ('Макароны', 'Макароны'), ('Тарты', 'Тарты'), ('Подарочные наборы', 'Подарочные наборы'), ('Комбо', 'Комбо'), ('Завтраки', 'Завтраки'), ('Кофе', 'Кофе'), ('Напитки', 'Напитки'), ('Десерты', 'Десерты'), ('Детские блюда', 'Детские блюда'), ('Акции', 'Акции')], max_length=50)),
                ('is_new', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('calories', models.IntegerField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
        ),
    ]
