# Generated by Django 5.1.1 on 2025-03-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_pickuppoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.pickuppoint', verbose_name='Точка приёма'),
        ),
    ]
